// Workflow + docs hygiene tests.
//
// Three contracts that protect this branch's housekeeping clean-up
// against silent regression in future PRs:
//
//   1. Each third-party action used in `.github/workflows/*.yml` is
//      pinned to a single commit-SHA across every workflow that
//      consumes it. The previous state had `actions/checkout` pinned
//      to TWO different SHAs (v4.2.2 + v6.0.2) within the same
//      `ci.yml` file, which made auditing painful and let drift creep
//      in invisibly.
//
//   2. No workflow lists a `cursor/**` PR-target branch. That pattern
//      came from a long-since-retired Cursor IDE workflow; leaving it
//      in confused new contributors and never matched any branch the
//      CI actually saw.
//
//   3. The four archived audit docs (UX_AUDIT_TASKS, AUDIT_REPORT,
//      ENTERPRISE_READINESS_AUDIT, ENTERPRISE_UX_REDESIGN_AUDIT) only
//      exist under `docs/archive/`. If a PR re-creates one of them at
//      its old top-level path, the audit chain breaks — readers see
//      two copies and the index doc points at the wrong one.
//
// All three checks are filesystem-only (no shell-out, no fetch), so
// they're cheap enough to run in the regular `npm test` pass.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const workflowsDir = path.join(repoRoot, ".github", "workflows");
const archiveDir = path.join(repoRoot, "docs", "archive");

function readWorkflows() {
  return fs.readdirSync(workflowsDir)
    .filter(f => f.endsWith(".yml") || f.endsWith(".yaml"))
    .map(f => ({
      name: f,
      content: fs.readFileSync(path.join(workflowsDir, f), "utf8"),
    }));
}

// ────────────────────────────────────────────────────────────────────
// 1. Action SHA consistency
// ────────────────────────────────────────────────────────────────────

test("each third-party GitHub Action is pinned to one canonical SHA across all workflows", () => {
  const workflows = readWorkflows();
  // Map action-name → Map(SHA → list of files that pin it). After the
  // run, any action with > 1 SHA is a drift bug.
  /** @type {Map<string, Map<string, string[]>>} */
  const pins = new Map();
  // Match `uses: <name>@<sha>` — only full 40-char SHAs are accepted.
  // We deliberately skip floating-tag refs like `@v6` or `@main` —
  // those are caught by Scorecard / a different lint, not this test.
  const re = /uses:\s+([^\s@]+)@([0-9a-f]{40})\b/g;

  for (const wf of workflows) {
    let m;
    while ((m = re.exec(wf.content)) !== null) {
      const [, name, sha] = m;
      if (!pins.has(name)) pins.set(name, new Map());
      const byHash = pins.get(name);
      if (!byHash.has(sha)) byHash.set(sha, []);
      byHash.get(sha).push(wf.name);
    }
  }

  const offenders = [];
  for (const [name, byHash] of pins) {
    if (byHash.size > 1) {
      const detail = [...byHash.entries()]
        .map(([sha, files]) => `    ${sha}  (${files.join(", ")})`)
        .join("\n");
      offenders.push(`  ${name} pinned to ${byHash.size} different SHAs:\n${detail}`);
    }
  }

  assert.equal(
    offenders.length,
    0,
    `action-SHA drift across workflows:\n${offenders.join("\n")}`,
  );
});

test("every action `uses:` line carries a comment with the human-readable version (`# vX.Y.Z`)", () => {
  // Pinning without a version comment is technically secure but
  // makes the diff unreadable for reviewers — they can't tell
  // whether a SHA bump is a patch or a major-version change. We
  // grep for `uses: <name>@<sha>` lines and require a `#` comment
  // on the same line. Built-in `actions/<name>` actions and any
  // local `./<path>` references skip the check.
  const workflows = readWorkflows();
  const offenders = [];
  for (const wf of workflows) {
    const lines = wf.content.split(/\r?\n/);
    lines.forEach((line, idx) => {
      const m = line.match(/uses:\s+([^\s@]+)@([0-9a-f]{40})\b/);
      if (!m) return;
      // Require a `#` comment somewhere after the SHA on the same
      // line. The CI generated by GitHub itself uses this convention.
      const afterSha = line.slice(line.indexOf(m[2]) + 40);
      if (!/#\s*v?\d/.test(afterSha)) {
        offenders.push(`  ${wf.name}:${idx + 1} — \`${line.trim()}\` (missing # vX.Y.Z comment)`);
      }
    });
  }
  assert.equal(
    offenders.length,
    0,
    `actions pinned without a version comment:\n${offenders.join("\n")}`,
  );
});

// ────────────────────────────────────────────────────────────────────
// 2. cursor/** trigger removal
// ────────────────────────────────────────────────────────────────────

test("no workflow lists `cursor/**` as a PR-target branch", () => {
  const workflows = readWorkflows();
  const offenders = [];
  for (const wf of workflows) {
    if (wf.content.includes('"cursor/**"') || wf.content.includes("'cursor/**'")) {
      offenders.push(`  ${wf.name} still references the retired \`cursor/**\` PR-target trigger`);
    }
  }
  assert.equal(
    offenders.length,
    0,
    offenders.join("\n"),
  );
});

// ────────────────────────────────────────────────────────────────────
// 3. Archive integrity
// ────────────────────────────────────────────────────────────────────

test("the four archived audit docs live ONLY under docs/archive/", () => {
  // Every entry: { archivedName, originalName }. The originals must
  // not exist at their old top-level docs/ path.
  const archived = [
    { archived: "AUDIT_REPORT-2026-04-25.md", original: "AUDIT_REPORT.md" },
    { archived: "ENTERPRISE_READINESS_AUDIT-2026.md", original: "ENTERPRISE_READINESS_AUDIT.md" },
    { archived: "ENTERPRISE_UX_REDESIGN_AUDIT-2026.md", original: "ENTERPRISE_UX_REDESIGN_AUDIT.md" },
    { archived: "UX_AUDIT_TASKS-2026-04-25.md", original: "UX_AUDIT_TASKS.md" },
  ];

  const offenders = [];
  for (const { archived: archName, original } of archived) {
    const archPath = path.join(archiveDir, archName);
    if (!fs.existsSync(archPath)) {
      offenders.push(`  missing: docs/archive/${archName} (the archive entry must exist)`);
    }
    const origPath = path.join(repoRoot, "docs", original);
    if (fs.existsSync(origPath)) {
      offenders.push(`  duplicate: docs/${original} re-appeared after archive — delete it or update the test`);
    }
  }
  assert.equal(
    offenders.length,
    0,
    `archive-integrity violations:\n${offenders.join("\n")}`,
  );
});

// ────────────────────────────────────────────────────────────────────
// 4. Index docs reachable
// ────────────────────────────────────────────────────────────────────

test("the workflow + docs READMEs exist and are non-empty", () => {
  // A regression here means a PR accidentally removed an index doc
  // that other docs (and the repo root README) link to.
  const indexes = [
    path.join(workflowsDir, "README.md"),
    path.join(repoRoot, "docs", "README.md"),
    path.join(archiveDir, "README.md"),
  ];
  for (const p of indexes) {
    assert.ok(fs.existsSync(p), `index doc missing: ${path.relative(repoRoot, p)}`);
    const stat = fs.statSync(p);
    assert.ok(stat.size > 200, `index doc too small (looks gutted): ${path.relative(repoRoot, p)} (${stat.size} bytes)`);
  }
});
